name: reusable/lint
on:
  workflow_call:
    secrets:
      githubToken:
        description: "GitHub Token value"
        required: true

    inputs:
      tflintVersion:
        description: "Defines TFLint version to use"
        required: true
        type: string

      moduleRootDirectory:
        description: "Defines root module directory"
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.moduleRootDirectory }}
    steps:
      - name: Install TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ inputs.tflintVersion }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tflint -c ${{ github.workspace }}/.tflint.hcl --init && \
          tflint -c ${{ github.workspace }}/.tflint.hcl -f compact --minimum-failure-severity=error
